import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { DiagramFormat } from "../types.js";

export interface RenderResult {
  htmlPath: string;
  /** The raw diagram source written next to the HTML (.mermaid or .dot). */
  sourcePath: string;
  format: DiagramFormat;
}

/** File extension for the raw diagram source, per format. */
const SOURCE_EXT: Record<DiagramFormat, string> = { mermaid: ".mermaid", dot: ".dot" };

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/**
 * JSON literal safe to inline in a `<script>` block. `render_diagram` accepts
 * arbitrary diagram text, and a raw `</script>` in it would close the block
 * early and turn the remainder into live HTML. Escaping "<" removes that entirely.
 */
function jsonForScript(value: string): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

/** The format-specific diagram container + renderer script. */
function renderer(source: string, format: DiagramFormat): { body: string; script: string } {
  if (format === "dot") {
    return {
      body: '<div id="graph"></div>',
      script: `<script src="https://cdn.jsdelivr.net/npm/@viz-js/viz@3/lib/viz-standalone.js"></script>
<script>
  Viz.instance()
    .then((viz) => document.getElementById("graph").replaceChildren(viz.renderSVGElement(SRC)))
    .catch((e) => { document.getElementById("graph").textContent = "Could not render diagram: " + e; });
</script>`,
    };
  }
  return {
    body: `<pre class="mermaid">${escapeHtml(source)}</pre>`,
    script: `<script type="module">
  import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
  const dark = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
  mermaid.initialize({ startOnLoad: true, theme: dark ? "dark" : "default", securityLevel: "strict" });
</script>`,
  };
}

/** Self-contained HTML page that renders the diagram via CDN (Mermaid or Viz). */
function buildHtml(source: string, title: string, format: DiagramFormat): string {
  const safeTitle = escapeHtml(title);
  const preContent = escapeHtml(source);
  const { body, script } = renderer(source, format);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${safeTitle} — architecture</title>
<style>
  :root { color-scheme: light dark; --bg:#ffffff; --fg:#1a1a1a; --muted:#666; --card:#f6f8fa; --border:#e2e5e9; --accent:#3b6fd4; }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#0f1115; --fg:#e6e6e6; --muted:#9aa0a6; --card:#171a21; --border:#2a2f3a; --accent:#6f9dff; }
  }
  * { box-sizing: border-box; }
  body { margin:0; font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; background:var(--bg); color:var(--fg); }
  header { padding:20px 24px; border-bottom:1px solid var(--border); display:flex; align-items:baseline; gap:12px; flex-wrap:wrap; }
  header h1 { font-size:18px; margin:0; font-weight:650; }
  header .tag { font-size:12px; color:var(--muted); }
  main { padding:24px; }
  .diagram { background:var(--card); border:1px solid var(--border); border-radius:12px; padding:20px; overflow-x:auto; }
  .diagram .mermaid, .diagram #graph { display:flex; justify-content:center; }
  .diagram #graph svg { max-width:100%; height:auto; }
  .bar { display:flex; gap:8px; margin:16px 0 0; }
  button { font:inherit; font-size:13px; padding:7px 13px; border-radius:8px; border:1px solid var(--border); background:var(--card); color:var(--fg); cursor:pointer; }
  button:hover { border-color:var(--accent); }
  details { margin-top:16px; }
  summary { cursor:pointer; color:var(--muted); font-size:13px; }
  pre.src { background:var(--card); border:1px solid var(--border); border-radius:10px; padding:14px; overflow:auto; font-size:12.5px; line-height:1.5; }
  footer { padding:16px 24px; color:var(--muted); font-size:12px; border-top:1px solid var(--border); }
  a { color:var(--accent); }
</style>
</head>
<body>
<header>
  <h1>${safeTitle}</h1>
  <span class="tag">architecture diagram · draft · ${format}</span>
</header>
<main>
  <div class="diagram">
    ${body}
  </div>
  <div class="bar">
    <button id="copy">Copy ${format === "dot" ? "DOT" : "Mermaid"} source</button>
    <button id="download">Download ${SOURCE_EXT[format]}</button>
  </div>
  <details>
    <summary>View ${format === "dot" ? "DOT" : "Mermaid"} source</summary>
    <pre class="src">${preContent}</pre>
  </details>
</main>
<footer>Generated by <a href="https://github.com/builditwithgk/repo-cartographer" target="_blank" rel="noopener">repo-cartographer</a>. This is a draft — refine it with your model.</footer>
<script>
  const SRC = ${jsonForScript(source)};
  document.getElementById("copy").addEventListener("click", async () => {
    try { await navigator.clipboard.writeText(SRC); } catch (e) {}
  });
  document.getElementById("download").addEventListener("click", () => {
    const blob = new Blob([SRC], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = ${jsonForScript(title)} + ${JSON.stringify(SOURCE_EXT[format])};
    a.click();
    URL.revokeObjectURL(a.href);
  });
</script>
${script}
</body>
</html>
`;
}

/**
 * `render_diagram` — write a self-contained `.html` (renders via CDN: Mermaid
 * for mermaid source, Viz/Graphviz for DOT) plus the raw source file. `outPath`
 * may include an extension or not; both siblings are written from the same base.
 */
export function runRenderDiagram(
  source: string,
  outPath: string,
  format: DiagramFormat = "mermaid",
): RenderResult {
  if (!source.trim()) throw new Error("Refusing to render an empty diagram.");

  const base = outPath.replace(/\.(html|mermaid|dot)$/i, "");
  const htmlPath = resolve(`${base}.html`);
  const sourcePath = resolve(`${base}${SOURCE_EXT[format]}`);
  const title = base.split(/[\\/]/).pop() || "diagram";

  try {
    mkdirSync(dirname(htmlPath), { recursive: true });
    writeFileSync(sourcePath, source, "utf8");
    writeFileSync(htmlPath, buildHtml(source, title, format), "utf8");
  } catch (e) {
    throw new Error(`Could not write diagram files: ${e instanceof Error ? e.message : String(e)}`);
  }

  return { htmlPath, sourcePath, format };
}
